# Draws the appropriate hangman figure based on how many guesses the user has left
def print_hangman(guesses):
    if guesses == 0:
        print("   __________   ")
        print("   |         |  ")
        print("   |            ")
        print("   |            ")
        print("   |            ")
        print("   |            ")
        print("   |            ")
        print("___|___         ")
        print()
    elif guesses == 1:
        print("   __________   ")
        print("   |         |  ")
        print("   |         O  ")
        print("   |            ")
        print("   |            ")
        print("   |            ")
        print("   |            ")
        print("___|___         ")
        print()
    elif guesses == 2:
        print("   __________   ")
        print("   |         |  ")
        print("   |         O  ")
        print("   |         |  ")
        print("   |         |  ")
        print("   |            ")
        print("   |            ")
        print("___|___         ")
        print()
    elif guesses == 3:
        print("   __________   ")
        print("   |         |  ")
        print("   |         O  ")
        print("   |         |  ")
        print("   |         |  ")
        print("   |        /   ")
        print("   |            ")
        print("___|___         ")
        print()
    elif guesses == 4:
        print("   __________   ")
        print("   |         |  ")
        print("   |         O  ")
        print("   |         |  ")
        print("   |         |  ")
        print("   |        / \ ")
        print("   |            ")
        print("___|___         ")
        print()
    elif guesses == 5:
        print("   __________   ")
        print("   |         |  ")
        print("   |         O  ")
        print("   |        \|  ")
        print("   |         |  ")
        print("   |        / \ ")
        print("   |            ")
        print("___|___         ")
        print()
    elif guesses == 6:
        print("   __________   ")
        print("   |         |  ")
        print("   |         O  ")
        print("   |        \|/ ")
        print("   |         |  ")
        print("   |        / \ ")
        print("   |            ")
        print("___|___         ")
        print()
